### ISSUE TITLE
Typo in part1/cache_config.rst

### ISSUE THREAD

**Issue by szechuen** [powerjg/learning_gem5#1]
Not sure if this is the preferred channel for bug reporting. Apologize in advance if it isn't. 

There seems to be a typo in the \_\_init\_\_ function for L2Cache. 

\- super(L2Cache, self).\_\_init\_\_(options)
\+ super(L2Cache, self).\_\_init\_\_()

The attached .py has the correct code. 

Thanks for the clear and concise tutorial.

**Comment by powerjg** [comment]
Where are you seeing the issue?

I see in part1/cache_config.rst that I have the options parameter that shouldn't be there. Do you see it somewhere else too?

Thanks for the bug report!

**Comment by szechuen** [comment]
Sorry, forgot to escape my '\+' and '\-' so I may have been a little confusing. Think that's the only instance of the typo ;)
