### ISSUE TITLE
LTAGE aborts gem5

### ISSUE THREAD

**Issue by JohnKon98** [powerjg/learning_gem5#32]
Hi all,
I want to ask if you know anything about this backtrace message I have when I try to restore from a checkpoint with DerivO3CPU using LTAGE.

gem5.opt: build/X86/cpu/pred/ltage.cc:101: virtual void LTAGE::update(ThreadID, Addr, bool, void*, bool, const StaticInstPtr&, Addr): Assertion `corrTarget != MaxAddr' failed.
Program aborted at tick 30396466306134
--- BEGIN LIBC BACKTRACE ---
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(_Z15print_backtracev+0x15)[0xd87f45]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(_Z12abortHandleri+0x39)[0xd925e9]
/lib64/libpthread.so.0(+0xf7e0)[0x2add9f7cc7e0]
/lib64/libc.so.6(gsignal+0x35)[0x2adda1099495]
/lib64/libc.so.6(abort+0x175)[0x2adda109ac75]
/lib64/libc.so.6(+0x2b60e)[0x2adda109260e]
/lib64/libc.so.6(__assert_perror_fail+0x0)[0x2adda10926d0]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(_ZN5LTAGE6updateEsmbPvbRK14RefCountingPtrI10StaticInstEm+0x347)[0xea5c17]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(_ZN9BPredUnit6squashERKmRKN6X86ISA7PCStateEbs+0x21d)[0xe96a5d]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(_ZN12DefaultFetchI9O3CPUImplE21checkSignalsAndUpdateEs+0x30e)[0xefd3de]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(_ZN12DefaultFetchI9O3CPUImplE4tickEv+0x73)[0xf03583]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(_ZN9FullO3CPUI9O3CPUImplE4tickEv+0x5f)[0xee565f]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(_ZN10EventQueue10serviceOneEv+0xc5)[0xd8dd05]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(_Z9doSimLoopP10EventQueue+0x38)[0xd9ba68]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(_Z8simulatem+0xd3a)[0xd9cb3a]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt[0x152b70c]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt[0x998de1]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyEval_EvalFrameEx+0x5266)[0x15f0506]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyEval_EvalCodeEx+0x877)[0x15f2477]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyEval_EvalFrameEx+0x56f3)[0x15f0993]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyEval_EvalCodeEx+0x877)[0x15f2477]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyEval_EvalFrameEx+0x56f3)[0x15f0993]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyEval_EvalCodeEx+0x877)[0x15f2477]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyEval_EvalFrameEx+0x56f3)[0x15f0993]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyEval_EvalCodeEx+0x877)[0x15f2477]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyEval_EvalCode+0x32)[0x15f2582]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyEval_EvalFrameEx+0x5f69)[0x15f1209]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyEval_EvalCodeEx+0x877)[0x15f2477]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyEval_EvalFrameEx+0x56f3)[0x15f0993]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyEval_EvalCodeEx+0x877)[0x15f2477]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyEval_EvalCode+0x32)[0x15f2582]
/home/students/cs/2017/iconst01/EXTRASPACE/Gem5_Giannis/gem5/build/X86/gem5.opt(PyRun_StringFlags+0x11b)[0x161368b]
--- END LIBC BACKTRACE ---

This is the command I run :
build/X86/gem5.opt -d sim_gcc configs/example/fs.py --bench-image=gcc.img --script=gcc.rcS --cpu-type=DerivO3CPU --rel-max-tick=0 -r 22492288158 --at-instruction --checkpoint-dir=gcccpts/  --restore-with-cpu=DerivO3CPU --mem-size=8GB --caches --l2cache --num-l2caches=1 -I 100000000
Thanks in advance,
Giannis

**Comment by powerjg** [comment]
Hello,

For general gem5 questions, please use the gem5-users mailing list. You can sign up at http://www.gem5.org/mailman/listinfo/gem5-users and then send mail to gem5-users@gem5.org.
